In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
print("Hello")

Hello


In [11]:
#Import numpy library
import numpy as np

In [10]:
import numpy
arr=numpy.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [12]:
#for checking numpy version
import numpy as np
print(np.__version__)

1.26.4


In [13]:
#print 1D array
arr=np.array([42])
print(arr)

[42]


In [14]:
#print 2D array
arr=np.array([[1,2,3],[5,6,7]])
print(arr)

[[1 2 3]
 [5 6 7]]


In [17]:
#pritn 3D array
arr1=np.array([[1,2,3,4],[5,6,7,8],[2,5,7,9]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]
 [2 5 7 9]]


In [18]:
#checking dimensions
print(arr1.ndim)

2


In [20]:
#Accessing array elements
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [21]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [22]:
#array slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[1:5])

[2 3 4 5]


In [23]:
#nagative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[-3:-1])

[5 6]


In [24]:
#steping
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[1:6:2])

[2 4 6]


In [28]:
#Checking datatype
arr = np.array([1, 2, 3, 4,4.5,2.1,6.7,8.9]) 
print(arr.dtype) 

float64


In [26]:
#reshaping array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 
newarr = arr.reshape(4, 3) 
print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
#checking shape & size of array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) 
print(arr.shape) 
print(arr.size)

(2, 4)
8


In [30]:
#numpy array iterating
arr = np.array([1, 2, 3]) 
for x in arr: 
   print(x) 

1
2
3


In [27]:
#Concatenate/Joining array
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6]) 
arr = np.concatenate((arr1, arr2)) 
print(arr) 

[1 2 3 4 5 6]


In [40]:
#spliting array
arr = np.array([1, 2, 3, 4, 5, 6]) 
newarr = np.array_split(arr, 3) 
print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [41]:
#searching array
arr = np.array([1, 2, 3, 4, 5, 4, 4]) 
x = np.where(arr == 4) 
print(x) 

(array([3, 5, 6], dtype=int64),)


In [42]:
#sorting array
arr = np.array([3, 2, 0, 1]) 
print(np.sort(arr))

[0 1 2 3]


In [43]:
#for descending
arr = np.array([3, 2, 0, 1]) 
print(np.sort(arr)[::-1])

[3 2 1 0]


In [44]:
#filter array
arr = np.array([41, 42, 43, 44]) 
x = [True, False, True, False] 
newarr = arr[x] 
print(newarr) 

[41 43]


In [47]:
arr = np.array([41, 42, 43, 44]) 
# Create an empty list 
filter_arr = [] 
# go through each element in arr 
for element in arr: 
# if the element is higher than 42, set the value to True, otherwise False: 
 if element > 42: 
  filter_arr.append(True) 
 else: 
  filter_arr.append(False) 
newarr = arr[filter_arr] 
print(filter_arr) 
print(newarr) 

[False, False, True, True]
[43 44]


In [38]:
#Conversion of datatype
arr=np.array([1,2,3,4.2,5])
print(arr.dtype)
print(arr.astype(int))

float64
[1 2 3 4 5]


In [49]:
#Adding & removing elements
arr=np.array([20,30,40])
print(np.append(arr,[50,60]))
print(np.insert(arr,2,90)) 
print(np.delete(arr,[1]))

[20 30 40 50 60]
[20 30 90 40]
[20 40]


In [50]:
#Aggrigating functions
a=np.array([20,30,40,50])
print(np.sum(a))
#Minimum
print(np.min(a))
#Maximum
print(np.max(a))
#Cumulative sum
print(np.cumsum(a))

140
20
50
[ 20  50  90 140]


In [51]:
#Statistical functions
import statistics as stats
food_price=[20,30,40,50,60,20]
a=np.array(food_price)

#mean
print(np.mean(a))
#median
print(np.median(a))
#mode
print(stats.mode(a))

36.666666666666664
35.0
20
